sites = {
    "Facebook": "https://www.facebook.com/",
    "Instagram": "https://www.instagram.com/",
    "Twitter (X)": "https://twitter.com/",
    "LinkedIn": "https://www.linkedin.com/in/",
    "Reddit": "https://www.reddit.com/user/",
    "TikTok": "https://www.tiktok.com/@",
    "YouTube": "https://www.youtube.com/@",
    "Twitch": "https://www.twitch.tv/",
    "Pinterest": "https://www.pinterest.com/",
    "Tumblr": "https://.tumblr.com/",
    "Quora": "https://www.quora.com/profile/",
    "Medium": "https://medium.com/@",
    "VK": "https://vk.com/",
    "Snapchat": "https://www.snapchat.com/add/",
    "Telegram": "https://t.me/",
    "Discord": "https://discord.com/users/",
    "WhatsApp": "https://wa.me/",
    "Signal": "https://signal.me/#p/",
    "GitHub": "https://github.com/",
    "GitLab": "https://gitlab.com/",
    "Bitbucket": "https://bitbucket.org/",
    "Stack Overflow": "https://stackoverflow.com/users/",
    "Dev.to": "https://dev.to/",
    "CodePen": "https://codepen.io/",
    "Replit": "https://replit.com/@",
    "Figma": "https://figma.com/@",
    "Canva": "https://www.canva.com/",
    "Dribbble": "https://dribbble.com/",
    "Behance": "https://www.behance.net/",
    "Flickr": "https://www.flickr.com/people/",
    "500px": "https://500px.com/p/",
    "DeviantArt": "https://www.deviantart.com/",
    "ArtStation": "https://www.artstation.com/",
    "SoundCloud": "https://soundcloud.com/",
    "Spotify": "https://open.spotify.com/user/",
    "Bandcamp": "https://bandcamp.com/",
    "Mixcloud": "https://www.mixcloud.com/",
    "Last.fm": "https://www.last.fm/user/",
    "Steam": "https://steamcommunity.com/id/",
    "Epic Games": "https://www.epicgames.com/account/",
    "Xbox Live": "https://account.xbox.com/profile?gamertag=",
    "PlayStation Network": "https://my.playstation.com/profile/",
    "Battle.net": "https://battle.net/account/management/",
    "GOG.com": "https://www.gog.com/u/",
    "itch.io": "https://itch.io/profile/",
    "Roblox": "https://www.roblox.com/user.aspx?username=",
    "Minecraft": "https://www.minecraft.net/en-us/profile",
    "Fortnite Tracker": "https://fortnitetracker.com/profile/all/",
    "League of Legends": "https://www.op.gg/summoners/",
    "Dota 2": "https://www.dotabuff.com/players/",
    "CS:GO": "https://steamcommunity.com/id/",
    "Overwatch": "https://www.overbuff.com/players/",
    "PUBG": "https://pubg.op.gg/user/",
    "Apex Legends": "https://apex.tracker.gg/apex/profile/",
    "Call of Duty": "https://my.callofduty.com/",
    "Genshin Impact": "https://www.hoyolab.com/accountCenter/",
    "World of Warcraft": "https://worldofwarcraft.com/en-us/character/",
    "Destiny 2": "https://destinytracker.com/d2/profile/",
    "Path of Exile": "https://www.pathofexile.com/account/",
    "Warframe": "https://www.warframe.com/user",
    "EVE Online": "https://evewho.com/pilot/",
    "Hacker News": "https://news.ycombinator.com/user?id=",
    "Product Hunt": "https://www.producthunt.com/@",
    "Slashdot": "https://slashdot.org/~",
    "4chan": "https://boards.4chan.org/",
    "NeoGAF": "https://www.neogaf.com/members/",
    "Reddit (Old)": "https://old.reddit.com/user/",
    "Indie Hackers": "https://www.indiehackers.com/",
    "Stack Exchange": "https://stackexchange.com/users/",
    "Kaggle": "https://www.kaggle.com/",
    "HackerRank": "https://www.hackerrank.com/",
    "LeetCode": "https://leetcode.com/",
    "CodeChef": "https://www.codechef.com/users/",
    "Codewars": "https://www.codewars.com/users/",
    "Exercism": "https://exercism.org/profiles/",
    "Docker Hub": "https://hub.docker.com/u/",
    "npm": "https://www.npmjs.com/~",
    "PyPI": "https://pypi.org/user/",
    "NuGet": "https://www.nuget.org/profiles/",
    "RubyGems": "https://rubygems.org/profiles/",
    "Crates.io": "https://crates.io/users/",
    "WordPress": "https://profiles.wordpress.org/",
    "Blogger": "https://www.blogger.com/profile/",
    "Substack": "https://.substack.com/",
    "Ghost": "https://ghost.org/members/",
    "Hashnode": "https://hashnode.com/@",
    "Dev.to (Crypto)": "https://dev.to/",
    "Hackernoon": "https://hackernoon.com/u/",
    "Medium (Crypto)": "https://medium.com/@",
    "Mirror.xyz": "https://mirror.xyz/",
    "OpenSea": "https://opensea.io/",
    "Rarible": "https://rarible.com/user/",
    "Foundation": "https://foundation.app/@",
    "SuperRare": "https://superrare.com/",
    "Audius": "https://audius.co/",
    "Odysee": "https://odysee.com/@",
    "LBRY": "https://lbry.tv/@",
    "PeerTube": "https://peertube.tv/accounts/",
    "DTube": "https://d.tube/#!/",
    "Bitchute": "https://www.bitchute.com/channel/",
    "Rumble": "https://rumble.com/user/",
    "Vimeo": "https://vimeo.com/",
    "Dailymotion": "https://www.dailymotion.com/",
    "9GAG": "https://9gag.com/u/",
}