file_formats = [
    ".txt", ".doc", ".docx", ".pdf", ".rtf", ".odt", ".epub", ".mobi", ".fb2", ".djvu",
    ".xps", ".oxps", ".chm", ".pages", ".key", ".numbers", ".md", ".tex", ".log",
    ".xls", ".xlsx", ".csv", ".ods", ".xlsm", ".xlsb", ".tsv", ".dif", ".slk",
    ".ppt", ".pptx", ".odp", ".pps", ".ppsx", ".sdd", ".show",
    ".jpg", ".jpeg", ".png", ".gif", ".bmp", ".tiff", ".tif", ".webp", ".svg", ".ico",
    ".psd", ".ai", ".cdr", ".eps", ".raw", ".cr2", ".nef", ".arw", ".heic", ".avif",
    ".mp4", ".avi", ".mov", ".mkv", ".wmv", ".flv", ".webm", ".mpeg", ".mpg", ".3gp",
    ".m4v", ".vob", ".ogv", ".m2ts", ".ts", ".mxf", ".divx", ".rm", ".rmvb", ".asf",
    ".mp3", ".wav", ".flac", ".aac", ".ogg", ".wma", ".m4a", ".amr", ".mid", ".midi",
    ".aiff", ".ape", ".opus", ".ac3", ".dts", ".mka", ".wave", ".voc",
    ".zip", ".rar", ".7z", ".tar", ".gz", ".bz2", ".xz", ".iso", ".dmg", ".pkg",
    ".deb", ".rpm", ".msi", ".cab", ".arj", ".lzh", ".ace", ".arc",
    ".exe", ".msi", ".apk", ".app", ".bat", ".cmd", ".sh", ".bin", ".jar", ".com",
    ".pif", ".scr", ".vb", ".vbs", ".ps1", ".elf", ".dll", ".so", ".dylib", ".sys",
    ".html", ".htm", ".xhtml", ".css", ".js", ".php", ".asp", ".aspx", ".jsp",
    ".xml", ".json", ".yaml", ".yml", ".toml", ".ini", ".cfg", ".conf",
    ".py", ".java", ".cpp", ".c", ".h", ".cs", ".vb", ".fs", ".rb", ".go",
    ".rs", ".swift", ".kt", ".pl", ".pm", ".r", ".scala", ".m", ".mm", ".dart",
    ".sql", ".db", ".sqlite", ".mdb", ".accdb", ".dbf", ".mdf", ".frm", ".ibd",
    ".torrent", ".srt", ".ass", ".ssa", ".vtt", ".sub", ".idx",
    ".ttf", ".otf", ".woff", ".woff2", ".eot", ".fon",
    ".lnk", ".url", ".webloc", ".vcf", ".ics", ".pem", ".key", ".crt", ".csr",
    ".blend", ".ma", ".mb", ".max", ".3ds", ".obj", ".fbx", ".dae", ".stl", ".ply",
    ".dwg", ".dxf", ".igs", ".iges", ".step", ".stp", ".sat",
    ".gcode", ".nc", ".apt", ".cnc",
    ".pdb", ".pdbqt", ".mol", ".sdf", ".cif", ".xyz",
    ".hdr", ".exr", ".pic", ".raw", ".dng", ".orf", ".rw2", ".raf",
    ".ms", ".msg", ".pst", ".ost", ".eml", ".mbox",
    ".bak", ".tmp", ".temp", ".old", ".new", ".part", ".crdownload",
    ".theme", ".desktop", ".contact", ".group", ".library-ms"
]