from faker_engine import Russian_Faker

if __name__ == "__main__":
    rus_faker = Russian_Faker()
    print(f"Сегодняшняя дата: {rus_faker.get_now_date()}")
    print(f"Случайный год для документов: {rus_faker.random_year()}")
    print(f"Возраст: {rus_faker.age()} лет")
    print(f"День рождение: {rus_faker.year()}")
    print(f"Пол: {rus_faker.gender()}")
    print(f"Имя: {rus_faker.get_name()}")
    print(f"Фамилия: {rus_faker.get_surname()}")
    print(f"Отчество: {rus_faker.get_patronymic()}")
    print(f"Полное имя: {rus_faker.full_name()}")
    print(f"ИНН: {rus_faker.inn()}")
    print(f"СНИЛС: {rus_faker.snils()}")
    print(f"Серия паспорта: {rus_faker.passport_series()}")
    print(f"Номер паспорта: {rus_faker.passport_number()}")
    print(f"Код подразделения: {rus_faker.department_code()}")
    print(f"Группа крови: {rus_faker.get_blood()}")
    print(f"Медицинский полис: {rus_faker.get_medical_policy()}")
    print(f"Знак зодиака: {rus_faker.get_zodiac_sign()}")
    print(f"Электронная почта: {rus_faker.get_email()}")
    print(f"Почтовый индекс: {rus_faker.get_postal_code()}")
    print(f"Регион: {rus_faker.get_region()}")
    print(f"Город: {rus_faker.get_city()}")
    print(f"Улица: {rus_faker.get_street()}")
    print(f"Полный адрес: {rus_faker.get_full_address()}")
    print(f"Банк: {rus_faker.get_bank_name()}")
    print(f"БИК: {rus_faker.get_bik()}")
    print(f"КПП: {rus_faker.get_kpp()}")
    print(f"Расчётный счёт: {rus_faker.get_payment_account()}")
    print(f"Номер карты: {rus_faker.get_card_number()}")
    print(f"Тип карты: {rus_faker.get_card_type()}")
    print(f"Срок действия: {rus_faker.get_card_expiry()}")
    print(f"CVV: {rus_faker.get_cvv()}")
    print(f"Телефон: {rus_faker.get_phone_number()}")
    print(f"Оператор: {rus_faker.get_mobile_operator()}")
    print(f"Должность: {rus_faker.get_job_title()}")
    print(f"Стаж работы: {rus_faker.get_work_experience()}")
    print(f"Компания: {rus_faker.get_company()}")
    print(f"Зарплата: {rus_faker.get_salary()} руб")
    print(f"Образование: {rus_faker.get_education()}")
    print(f"Колледж: {rus_faker.get_college()}")
    print(f"ВУЗ: {rus_faker.get_university()}")
    print(f"ОГРН: {rus_faker.get_ogrn()}")
    print(f"ОГРНИП: {rus_faker.get_ogrnip()}")
    print(f"Полис ОМС: {rus_faker.compulsory_medical_insurance_policy()}")
    print(f"Категории Водительского Удостоверения: {rus_faker.get_driver_license_category()}")
    print(f"Серия Водительского Удостоверения: {rus_faker.driver_license_series()}")
    print(f"Номер Водительского Удостоверения: {rus_faker.driver_license_number()}")
    print(f"Регистрационный знак: {rus_faker.registration_mark()}")
    print(f"Серия и Номер Свидетельства о регистрации ТС: {rus_faker.vehicle_registration_certificate()}")
    print(f"Серия и Номер Военного билета: {rus_faker.military_ticket()}")
    print(f"Рост: {rus_faker.get_height()} см")
    print(f"Вес: {rus_faker.get_weight()} кг")
    print(f"Цвет глаз: {rus_faker.get_eye_color()}")
    print(f"Цвет волос: {rus_faker.get_hair_color()}")