# Generated by Django 5.2.1 on 2025-07-08 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('nickname', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(11)])),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('Yes', 'Решено'), ('No', 'Не решено')], default='Не решено')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_category', models.CharField(choices=[('Ads', 'Объявления'), ('Special Events', 'Мероприятия'), ('Common events', 'Общие события')], default='Общие события')),
                ('audience_category', models.CharField(choices=[('For parents', 'Для родителей'), ('For students', 'Для учеников'), ('For teachers', 'Для учителей')], default='Для учеников')),
                ('thematic_category', models.CharField(choices=[('Sport', 'Спорт'), ('Science', 'Наука'), ('Creation', 'Творчество'), ('Safety', 'Безопасность')], default='Наука')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=120, unique=True)),
                ('text', models.TextField()),
                ('photo', models.ImageField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo_teacher/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.IntegerField(validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(11)])),
                ('telegram', models.CharField(blank=True, max_length=50)),
                ('room', models.IntegerField()),
                ('education', models.TextField()),
                ('qualification', models.CharField(max_length=70)),
                ('work_experience', models.IntegerField()),
                ('short_bio', models.TextField(max_length=500)),
                ('position', models.ManyToManyField(to='school_30.position')),
                ('subjects', models.ManyToManyField(to='school_30.subjects')),
            ],
        ),
    ]
