# Generated by Django 5.2.1 on 2025-07-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_30', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(),
        ),
    ]
