# Generated by Django 5.2.1 on 2025-07-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_30', '0002_alter_feedback_phone_alter_staff_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255, unique=True)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=120)),
                ('salary', models.IntegerField()),
                ('text', models.TextField()),
                ('is_actual', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default='Да', max_length=3)),
            ],
        ),
    ]
