# Generated by Django 5.2.1 on 2025-07-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_30', '0003_sponsors_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='mail',
            field=models.EmailField(default='no-email@example.com', max_length=254),
        ),
    ]
