# Generated by Django 5.2.1 on 2025-07-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_30', '0004_feedback_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooldocument',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
