# Generated by Django 5.2.4 on 2025-07-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('surname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(max_length=5000)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='cooperation/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='cooperation/')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('surname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(blank=True, max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(max_length=5000)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='feedback/')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('company', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('year', models.IntegerField()),
                ('trailer', models.URLField(blank=True, max_length=255)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='games/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='games/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='games/')),
                ('presentation', models.FileField(blank=True, null=True, upload_to='presentation/')),
                ('document1', models.FileField(blank=True, null=True, upload_to='document/')),
                ('document2', models.FileField(blank=True, null=True, upload_to='document/')),
                ('document3', models.FileField(blank=True, null=True, upload_to='document/')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo1', models.ImageField(upload_to='news/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='news/')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('about', models.TextField(max_length=2000, unique=True)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('photo', models.ImageField(upload_to='products/')),
                ('urls', models.URLField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('about', models.TextField(max_length=3000, unique=True)),
                ('photo', models.ImageField(upload_to='sponsors/')),
                ('surname_d', models.CharField(max_length=255)),
                ('name_d', models.CharField(max_length=255)),
                ('patronymic_d', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('financing', models.IntegerField()),
                ('url', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField()),
                ('position', models.CharField(choices=[('GD', 'Геймдизайнер'), ('LD', 'Ведущий геймдизайнер'), ('NLD', 'Нарративный дизайнер'), ('LVLD', 'Левел-дизайнер'), ('PD', 'Продуктовый дизайнер'), ('PRG', 'Программист'), ('CPRG', 'Ведущий программист'), ('GPRG', 'Геймплей-программист'), ('GPRG', 'Графический программист'), ('TPRG', 'Инструментальный программист'), ('AI', 'Программист ИИ'), ('ART', 'Художник'), ('CART', 'Арт-директор'), ('2D', '2D-художник'), ('3D', '3D-художник'), ('CHAR', 'Художник по персонажам'), ('ENV', 'Художник окружения'), ('VFX', 'Художник VFX'), ('TECHART', 'Технический художник'), ('ANIM', 'Аниматор'), ('CANIM', 'Ведущий аниматор'), ('SND', 'Звукорежиссер'), ('COMP', 'Композитор'), ('VA', 'Режиссер озвучки'), ('QA', 'Тестировщик'), ('LEADQA', 'Ведущий тестировщик'), ('AQA', 'Автоматизатор тестирования'), ('PM', 'Продюсер'), ('APM', 'Ассоциированный продюсер'), ('SPM', 'Старший продюсер'), ('MKT', 'Маркетолог'), ('CM', 'Менеджер комьюнити'), ('SM', 'Соцмедиа менеджер'), ('HR', 'HR-специалист'), ('RECR', 'Рекрутер'), ('ADM', 'Администратор'), ('ACC', 'Бухгалтер'), ('LAW', 'Юрист'), ('CEO', 'Генеральный директор'), ('CTO', 'Технический директор'), ('COO', 'Операционный директор'), ('CFO', 'Финансовый директор')], default='PRG', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('experience', models.IntegerField()),
                ('about', models.TextField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=2000)),
                ('experience', models.IntegerField()),
                ('price', models.IntegerField()),
                ('experience_level', models.CharField(choices=[('TRAINEE', 'Трени'), ('INTERN', 'Интерн'), ('JUNIOR', 'Джуниор'), ('JUNIOR+', 'Джуниор+'), ('MIDDLE', 'Миддл'), ('MIDDLE+', 'Миддл+'), ('SENIOR', 'Сеньор'), ('SENIOR+', 'Сеньор+'), ('LEAD', 'Лид'), ('SLEAD', 'Старший лид'), ('ARCHITECT', 'Архитектор'), ('PM', 'Менеджер проекта'), ('HOD', 'Руководитель отдела'), ('DIRECTOR', 'Директор')], default='JUNIOR', max_length=20)),
                ('is_actual', models.CharField(choices=[('ACTIVE', 'Актуально'), ('INACTIVE', 'Неактуально'), ('ARCHIVED', 'В архиве'), ('DRAFT', 'Черновик')], default='DRAFT', max_length=15)),
                ('photo1', models.ImageField(upload_to='')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='')),
                ('phone', models.CharField()),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
