# Generated by Django 5.2.4 on 2025-07-31 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('/0day/', '/0day/'), ('/malware/', '/malware/'), ('/opsec/', '/opsec/'), ('/carding/', '/carding/'), ('/leaks/', '/leaks/'), ('/b/', '/b/')], default='/b/', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nickname', models.CharField(blank=True, default='Anonymus', max_length=255)),
                ('text', models.TextField(max_length=5000)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='post/')),
                ('file', models.FileField(blank=True, null=True, upload_to='post/')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nickname', models.CharField(blank=True, default='Anonymus', max_length=255)),
                ('text', models.TextField(max_length=5000)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='post/')),
                ('file', models.FileField(blank=True, null=True, upload_to='post/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='analog.post')),
            ],
        ),
    ]
